import { type TProductCardInfo } from 'components/product-cards/product-card';
import { type TCharacteristic } from 'types/product';
import img1 from './assets/Rectangle 41.png';
import img2 from './assets/Rectangle 42.png';
import img3 from './assets/Rectangle 43.png';

export const DEFAULT_TITLE = 'Строительные смеси';

export const productCharacteristics: TCharacteristic[] = [
  { id: 0, prop: 'Производитель:', value: 'БЦК' },
  { id: 1, prop: 'Артикул:', value: '31120' },
  { id: 2, prop: 'Вес:', value: '25 кг' },
];

export const productCards: TProductCardInfo[] = [
  {
    id: 0,
    imgSrc: img1,
    link: 'id0',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 1,
    imgSrc: img2,
    link: 'id1',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 2,
    imgSrc: img3,
    link: 'id2',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 3,
    imgSrc: img1,
    link: 'id3',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 4,
    imgSrc: img2,
    link: 'id4',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 5,
    imgSrc: img3,
    link: 'id5',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 6,
    imgSrc: img1,
    link: 'id6',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 7,
    imgSrc: img2,
    link: 'id7',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 8,
    imgSrc: img3,
    link: 'id8',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 9,
    imgSrc: img1,
    link: 'id9',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 10,
    imgSrc: img2,
    link: 'id10',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 11,
    imgSrc: img3,
    link: 'id11',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 12,
    imgSrc: img1,
    link: 'id12',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 13,
    imgSrc: img2,
    link: 'id13',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 14,
    imgSrc: img3,
    link: 'id14',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 15,
    imgSrc: img1,
    link: 'id15',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 16,
    imgSrc: img2,
    link: 'id16',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 17,
    imgSrc: img3,
    link: 'id17',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 18,
    imgSrc: img1,
    link: 'id18',
    isAvailable: true,
    title: 'Штукатурка цементная Ceresit, 25 кг',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 19,
    imgSrc: img2,
    link: 'id19',
    isAvailable: true,
    title: 'Лист оцинкованный 0,50х1250х1000 мм',
    productCharacteristics: productCharacteristics,
  },
  {
    id: 20,
    imgSrc: img3,
    link: 'id20',
    isAvailable: true,
    title: 'Черепица рулонная Технониколь МИНИ S2, 5м2, красная',
    productCharacteristics: productCharacteristics,
  },
];
